### PR TITLE
Improve Windows compatibility

### LINKED ISSUE #121: go-generate:  invalid UTF-8 encoding
After running go generate and trying to build the example, I get the following error: 

```
.\dot_product_amd64.s:11:6: invalid UTF-8 encoding
.\dot_product_amd64.s:11:6: invalid UTF-8 encoding
.\dot_product_amd64.s:11: expected '(', found DotProduct
asm: assembly of .\dot_product_amd64.s failed
```

I turns out that changing
`TEXT ·DotProduct(SB),4,$0-28`
to 
`TEXT Â·DotProduct(SB),4,$0-28`
solves the issue. 

i.e.: the byte `c2` is missing before the function name declaration.

So, I'm new to go ASM, thus I have no idea of what is going on her. 

I'm using `go1.18.2 windows/amd64`

### PR DESCRIPTION
**Pull request by ydylla**
Hi,
this improves the Windows compatibility of PeachPy.
In particular, it fixes #121. The problem was under Windows the default encoding for `open()` is `cp1252` instead of `utf-8`. So by always using `utf-8` for the `TextWriter` it is now possible to generate Go asm under Windows.

The second commit deals with the problems described in PR #43. Under Windows it is not possible to unlink an open file. With this the writers close the file before attempting to unlink it. Just like @bawr described in his [last comment](https://github.com/Maratyszcza/PeachPy/pull/43#issuecomment-223515563) but apparently never did.

Closes #121, closes #43

### CODE REVIEW

**Review by Maratyszcza — APPROVED** [review]
Thank you!

**Review by Maratyszcza — CHANGES_REQUESTED** [review]
Replace `open` with `codecs.open` for Python 2.7 compatibility

**Comment by ydylla** [comment]
Did not know python 2 does not have the encoding parameter 😄   
I also found `io.open` which I think is nicer than `codecs.open` because in Python 3 it's just an alias.

**Comment by ydylla** [comment]
```
File "codegen\x86_64.py", line 1152, in main
        print(str(code), file=out)
    TypeError: write() argument 1 must be unicode, not str
```
Well looks like I have to actually install Python 2.7 again and really test this 🙃

**Comment by ydylla** [comment]
Hmm I am out of ideas (and time) how to solve this correctly.  
Just switching to `codecs.open` makes the tests work for all python versions. But go asm would still be broken for python 2.7 (apparently there is no test that covers this).

When executing the go example with Python 2.7 and `codecs.open` I get this:
```
(venv) G:\Code\PeachPy\examples\go-generate>python -m peachpy.x86_64 dot_product.py -S -o dot_product_amd64.s -mabi=goasm
Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "g:\code\peachpy\peachpy\x86_64\__main__.py", line 283, in <module>
    main()
  File "g:\code\peachpy\peachpy\x86_64\__main__.py", line 270, in main
    execute_script(writers, options.input[0])
  File "g:\code\peachpy\peachpy\x86_64\__main__.py", line 201, in execute_script
    execute_script(writers, source_filename)
  File "g:\code\peachpy\peachpy\writer.py", line 27, in __exit__
    self.output_file.write(self.serialize())
  File "C:\Python27\lib\codecs.py", line 708, in write
    return self.writer.write(data)
  File "C:\Python27\lib\codecs.py", line 369, in write
    data, consumed = self.encode(object, self.errors)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 143: ordinal not in range(128)
```
and with `io.open` this (same as in the pipeline):
```
(venv) G:\Code\PeachPy\examples\go-generate>python -m peachpy.x86_64 dot_product.py -S -o dot_product_amd64.s -mabi=goasm
Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "g:\code\peachpy\peachpy\x86_64\__main__.py", line 283, in <module>
    main()
  File "g:\code\peachpy\peachpy\x86_64\__main__.py", line 270, in main
    execute_script(writers, options.input[0])
  File "g:\code\peachpy\peachpy\x86_64\__main__.py", line 201, in execute_script
    execute_script(writers, source_filename)
  File "g:\code\peachpy\peachpy\writer.py", line 27, in __exit__
    self.output_file.write(self.serialize())
TypeError: write() argument 1 must be unicode, not str
```

The `io.open` one can be fixed by adding decode before writing. But this is python 2.7 specific and gets rather ugly since it has to happen before each write (probably in various places):
```python
content = self.serialize()
if sys.version_info.major == 2:
    content = content.decode("utf-8")
self.output_file.write(content)
```

So which version do you prefer? Using `codecs.open` and wait until someone actually complains that go asm with python 2.7 does not work. Or using `io.open` with `sys.version_info.major == 2` in various places?
Or maybe you can think of a better solution.

**Comment by ydylla** [comment]
I will close this because I do not intend to spend time on fixing python2 support.  
Especially since I also switched to https://github.com/mmcloughlin/avo for generating go assembly, which just works under windows.

**Pull request closed without merging**
